# Generated by Django 5.1.3 on 2024-12-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_business_pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbusinesspricing",
            name="로밍평균요금",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
