# Generated by Django 5.1.3 on 2024-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='drive_range',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
