# Generated by Django 5.1.3 on 2024-11-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_drive_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='charge_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
