# Generated by Django 5.1.3 on 2024-12-04 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.CharField(
                        choices=[("WIN", "승리"), ("DRAW", "무승부")], max_length=255
                    ),
                ),
                ("playerCount", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "game",
            },
        ),
        migrations.CreateModel(
            name="GameWinnerInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winner_info",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winning_games",
                        to="player.player",
                    ),
                ),
            ],
            options={
                "db_table": "game_winner_info",
            },
        ),
        migrations.CreateModel(
            name="GamePlayerInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="player.player",
                    ),
                ),
            ],
            options={
                "db_table": "game_player_info",
                "unique_together": {("game", "player")},
            },
        ),
    ]
